# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #  branches: [ GitHub_Actions ]
  #pull_request:
  #  branches: [ GitHub_Actions ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set Version
        run: |
          echo "NEW_VERSION=2.1.7" >> $GITHUB_ENV
          echo "NEW_BRANCH_VERSION=2_1_7" >> $GITHUB_ENV
      - name: Update Version (updateVersions.sh)
        run: bash -x ./scripts/updateVersions.sh ${{ env.NEW_VERSION }}
      - name: Update Version (version.properties)
        run: sed -i 's/CURRENT_VERSION=.*/CURRENT_VERSION=${{ env.NEW_VERSION }}/' scripts/version.properties
      - uses: test-room-7/action-update-file@v1
        with:
          file-path: "**/pom.xml"
          branch: BLAZEGRAPH_RELEASE_${{ env.NEW_BRANCH_VERSION }}_RC
          commit-msg: Release Version Updates for ${{ env.NEW_BRANCH_VERSION }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
  release:
    needs: update_version
    runs-on: ubuntu-latest
    steps:
      - name: Set Version
        run: |
          echo "NEW_VERSION=2.1.7" >> $GITHUB_ENV
          echo "NEW_BRANCH_VERSION=2_1_7" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Release (Parent POM)
        run: mvn -f pom.xml clean install -DskipTests=true -N
      - name: Release (Build modules)
        run: mvn -f pom.xml clean install -DskipTests=true 
      - name: Release (Package JAR)
        run: mvn -f pom.xml clean install -P Deployment -U -DskipTests=true --projects blazegraph-jar,bigdata-jar
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: repository/com/blazegraph/blazegraph-jar/*/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          
          
